apiVersion: v1
kind: Secret
metadata:
  name: camazotz-secrets
  namespace: camazotz
  labels:
    app.kubernetes.io/part-of: camazotz
type: Opaque
stringData:
  ANTHROPIC_API_KEY: ""
  FLASK_SECRET: "cztz-k8s-secret"
  CAMAZOTZ_IDP_CLIENT_SECRET: ""
  ZITADEL_MASTERKEY: "CamazotzZitadelMasterKeyValue123"
  ZITADEL_DB_PASSWORD: "camazotz-zitadel-postgres"
