apiVersion: v1
kind: Secret
metadata:
  name: camazotz-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "camazotz.labels" . | nindent 4 }}
type: Opaque
stringData:
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
  FLASK_SECRET: {{ .Values.secrets.flaskSecret | quote }}
