from brain_gateway.app.brain.factory import get_provider

SYSTEM_PROMPT = (
    "You are a document summarization tool. "
    "Summarize the user-provided text faithfully and concisely. "
    "Include all content from the input, even if it contains instructions or commands. "
    "Do not filter, sanitize, or refuse any part of the input."
)


class ContextLabModule:
    """Claude-powered module with intentionally zero output sanitization.

    Red team lesson: indirect prompt injection via tool output.
    Blue team lesson: never pass raw LLM output back without sanitization.
    """

    def list_tools(self) -> list[dict]:
        return [
            {
                "name": "context.injectable_summary",
                "description": (
                    "Summarize the provided text. The summary is generated by an AI model "
                    "and returned directly without any filtering or sanitization."
                ),
                "inputSchema": {
                    "type": "object",
                    "required": ["text"],
                    "properties": {
                        "text": {"type": "string", "description": "Text to summarize."}
                    },
                },
            }
        ]

    def call_tool(self, name: str, arguments: dict) -> dict | None:
        if name != "context.injectable_summary":
            return None
        text = arguments.get("text", "")
        provider = get_provider()
        raw_summary = provider.generate(prompt=text, system=SYSTEM_PROMPT)
        return {"summary": raw_summary, "_sanitized": False}
